version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    container_name: python_app
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ../prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile    # este Dockerfile está dentro de ./grafana/Dockerfile
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin" 
    depends_on:
      - prometheus


volumes:
  # opcional, para persistir dados do Grafana
  grafana-data:
    name: grafana-data
