version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    container_name: python_app
    environment:
      FLASK_APP: main.py
    volumes:
      - ..:/app
    ports:
      - "5000:5000"
    command: ["python", "main.py"]